### PR TITLE
use OrbitControls, now it works on mobile

### LINKED ISSUE #2: Use Three.js OrbitControls for navigation
Instead of maintaining your own navigation code, why not use the existing OrbitControls or one of the others? The Detector.js file you are currently using is  a Three.js component, now named WebGL.js in the examples directory. It would not be difficult to use the existing controls as well and save yourself some effort in the future.

### LINKED ISSUE #10: mobile doesnot interactive
goto https://jerryi.github.io/Mathematica-ThreeJS-graphics-engine/

into mobile mode.

image

It stuck. (But I don't know the reason.)

### PR DESCRIPTION
**Pull request by wuyudi**
fix #2
fix #10

### CODE REVIEW

**Comment by JerryI** [comment]
Great job, @wuyudi 😇

**Comment by paulmasson** [comment]
@JerryI the live demo on the web doesn't work on mobile

**Comment by JerryI** [comment]
@paulmasson, the live demo takes a bundle file from the release folder. I moved the recent one to there. I guess, we just need to wait until CDN will clear the cache.

**Comment by JerryI** [comment]
upd: that's strange, still did not work. I will check it

**Comment by JerryI** [comment]
ok. I am an idiot. I forgot to recompile the bundle. Sorry for unnecessary commits.

**Pull request merged**
